base_url = "https://www.eunchan.kim"
title = "Eli Kim"
description = "Eli's Personal Website."
default_language = "ko"

compile_sass = false
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [
    { name = "tags", feed = true },
    { name = "categories", feed = true },
]

[markdown]
render_emoji = true

[search]
include_title = true
include_description = true
include_content = true
index_format = "elasticlunr_javascript"

[extra]
author = "Eli Kim"
copyright = "&copy; 2013 Elijah Kim"
repo_url = "https://github.com/eunchan/eunchan.github.io"
repo_name = "GitHub"

menu = [
    { name = "Articles", url = "/article/", children = [
        { name = "Posts", url = "/article/" },
        { name = "Research", url = "/research/" },
        { name = "Review", url = "/review/" },
        { name = "Tips", url = "/tips/" },
    ]},
    { name = "Journal", url = "/blog/" },
    { name = "Travel", url = "/travel/", children = [
        { name = "Overview", url = "/travel/" },
        { name = "North California", url = "/travel/norcal/" },
        { name = "Hawaii '15", url = "/travel/hawaii15/" },
        { name = "New Zealand '10", url = "/travel/new-zealand/" },
        { name = "Egypt '09", url = "/travel/egypt09/" },
        { name = "Tokyo", url = "/travel/tokyo/" },
        { name = "Europe '07", url = "/travel/europe/" },
        { name = "Canada Working Holiday", url = "/working-holiday/" },
    ]},
    { name = "Hobby", url = "/hobby/", children = [
        { name = "Motorcycle", url = "/motorcycle/" },
        { name = "Camping", url = "/camping/" },
        { name = "Nightsky", url = "/sky/" },
    ]},
    { name = "About", url = "/eunchan/" },
]

[extra.giscus]
repo = "eunchan/eunchan.github.io"
repo_id = "R_kgDOM4oq_g"
category = "General"
category_id = "DIC_kwDOM4oq_s4Ci4pi"
mapping = "pathname"
theme = "preferred_color_scheme"
lang = "ko"
