base_url = "https://www.eunchan.kim"
title = "Eli Kim"
description = "Eli's Personal Website."
default_language = "ko"
use_directory_urls = false

compile_sass = true
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [
    { name = "tags", feed = true },
    { name = "categories", feed = true },
]

[permalinks]
"blog/posts" = "blog/{year}/{slug}"


[markdown]
render_emoji = true
bottom_footnotes = true

[search]
include_title = true
include_description = true
include_content = true
index_format = "elasticlunr_javascript"

[extra]
author = "Eli Kim"
copyright_start_year = 2013
copyright_name = "Elijah Kim"
repo_url = "https://github.com/eunchan/eunchan.github.io"
repo_name = "GitHub"

menu = [
    { name = "Articles", url = "/article/", children = [
        { name = "Overview", url = "/article/" },
        { name = "Silicon & Hardware", url = "/article/silicon/" },
        { name = "Systems & Tools", url = "/article/systems/" },
        { name = "Reviews & Setups", url = "/article/review/" },
    ]},
    { name = "Journal", url = "/blog/" },
    { name = "Travel", url = "/travel/" },
    { name = "Hobby", url = "/hobby/", children = [
        { name = "Motorcycle", url = "/motorcycle/" },
        { name = "Camping", url = "/camping/" },
        { name = "Nightsky", url = "/sky/" },
    ]},
    { name = "About", url = "/eunchan/" },
]

[extra.giscus]
repo = "eunchan/eunchan.github.io"
repo_id = "R_kgDOM4oq_g"
category = "General"
category_id = "DIC_kwDOM4oq_s4Ci4pi"
mapping = "pathname"
theme = "preferred_color_scheme"
lang = "ko"
