site_name: Eli Kim
site_url: https://www.eunchan.kim
site_description: Eli's Personal Website.
use_directory_urls: false
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  #font:
  #  text: Atkinson Hyperlegible, Pretendard
  #  code: Monaspace Neon
  language: ko
  logo: static/img/logo2.png
  custom_dir: overrides
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - content.action.edit
  palette:
    scheme: default
    primary: white
    accent: teal
plugins:
  # - meta
  - blog:
      post_url_date_format: yyyy
  - search
  # - social
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: "date" # means from page.meta.date
        as_update: "git" # means from git log
        datetime_format: "%Y-%m-%d"
        default_time: "23:00"
        default_timezone: America/Los_Angeles
      feeds_filenames:
        rss_created: rss.xml
        rss_updated: rss_updated.xml
      length: 20
      rss_feed_enabled: true
      use_git: true
      categories:
        - categories
        - tags
  - git-revision-date-localized:
      enable_creation_date: true
  - extra-sass
nav:
  - articles:
    - article/index.md
    - review/index.md
  - journal:
    - blog/index.md
  - travel
  - hobby:
    - motorcycle/index.md
  - eunchan/index.md
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
  generator: false
  #social:
  #  - type: "linkedin"
  #    link: "https://linkedin.com/in/eunchankim"
repo_url: https://github.com/eunchan/elijah.kim
repo_name: eunchan/elijah.kim
edit_uri: edit/main/docs/
markdown_extensions:
  - attr_list
  - tables
  - footnotes
validation:
  omitted_files: warn
  absolute_links: relative_to_docs
  unrecognized_links: warn
  anchors: warn
copyright: Copyright &copy; 2013 - 2024 Elijah Kim