site_name: Eli Kim
site_url: https://www.eunchan.kim
site_description: Eli's Personal Website.
use_directory_urls: false
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  #font:
  #  text: Atkinson Hyperlegible, Pretendard
  #  code: Monaspace Neon
  language: ko
  logo: static/img/logo2.png
  custom_dir: overrides
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.prune
    # - navigation.indexes
    - content.action.edit
  palette:
    scheme: default
    primary: white
    accent: teal
plugins:
  # - meta
  - blog:
      post_url_date_format: yyyy
      categories_toc: false
      archive_toc: false
  - blog:
      blog_dir: sky
      post_url_date_format: yyyy
      post_dir: "{blog}/log"
      categories_toc: false
      archive_toc: false
  - search
  # - social
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: "date" # means from page.meta.date
        as_update: "git" # means from git log
        datetime_format: "%Y-%m-%d"
        default_time: "23:00"
        default_timezone: America/Los_Angeles
      feeds_filenames:
        rss_created: rss.xml
        rss_updated: rss_updated.xml
      length: 20
      rss_feed_enabled: true
      use_git: true
      categories:
        - categories
        - tags
  - git-revision-date-localized:
      enable_creation_date: true
  - extra-sass
nav:
  - Articles:
    - Posts: article/index.md
    - research/index.md
    - review/index.md
    - tips/index.md
  - Journal:
    - blog/index.md
  - Travel:
    - travel/index.md
    - travel/norcal/index.md
    - 하와이 '15:
      - travel/hawaii15/index.md
      - travel/hawaii15/gallery.md
    - 뉴질랜드 신혼여행 '10:
      - travel/new-zealand/index.md
      - travel/new-zealand/campervan.md
      - travel/new-zealand/route.md
      - travel/new-zealand/log01.md
      - travel/new-zealand/log02.md
      - travel/new-zealand/log03.md
      - travel/new-zealand/log04.md
      - travel/new-zealand/log05.md
      - travel/new-zealand/log06.md
      - travel/new-zealand/log07.md
      - travel/new-zealand/log08.md
      - travel/new-zealand/log09.md
      - travel/new-zealand/log10.md
      - travel/new-zealand/epilogue.md
      - travel/new-zealand/gallery-wide.md
      - travel/new-zealand/gallery.md
    - 이집트 '09:
      - travel/egypt09/index.md
      - travel/egypt09/gallery.md
    - 도쿄:
      - travel/tokyo/index.md
      - travel/tokyo/gallery.md
    - 유럽 '07:
      - travel/europe/index.md
      - travel/europe/001backpacking.md
      - travel/europe/002route.md
      - travel/europe/003expense.md
      - travel/europe/004depart.md
      - travel/europe/005newyorknewyork.md
      - travel/europe/006passionateitaly.md
      - travel/europe/007passionateitaly.md
      - travel/europe/008wienpraha.md
      - travel/europe/009fussen.md
      - travel/europe/010swiss.md
      - travel/europe/011swiss.md
      - travel/europe/012paris.md
      - travel/europe/013paris.md
      - travel/europe/014paris.md
      - travel/europe/015paris.md
      - travel/europe/016london.md
      - travel/europe/gallery.md
    - 캐나다 워홀:
      - working-holiday/index.md
      - 비자획득: working-holiday/01visaget.md
      - 신체검사: working-holiday/02physicalcheckup.md
      - 새로운 기회: working-holiday/03anotherchance.md
      - 미국으로 가기: working-holiday/04gotoamerica.md
      - 지원동기서: working-holiday/05essay.md
      - 유용한 정보: working-holiday/06usefulinfo.md
      - 준비할 것들: working-holiday/07prepare.md
      - 미국비자 인터뷰: working-holiday/08usavisainterview.md
      - 항공권 구하기: working-holiday/09ticket.md
      - 짐싸기: working-holiday/10pack.md
      - 밴쿠버 날아가기: working-holiday/11flytovancouver.md
      - 빅토리아 여행: working-holiday/12victoria.md
      - 밴프로 이동: working-holiday/13movetobanff.md
      - Mt.Rundle 등산: working-holiday/14hikingtorundle.md
      - into the Lakes: working-holiday/15intothelakes.md
      - 스노우보딩: working-holiday/16snowboarding.md
      - 만남, 그리고 이별: working-holiday/17meetingfarewell.md
      - 만남, 그리고 이별 2: working-holiday/18meetingfarewell2.md
      - 다른 방으로 이동: working-holiday/19movetoanotherroom.md
      - 워킹퍼밋, 그리고 이민: working-holiday/20workingpermitandimmigration.md
      - 워홀러에게 중요한 10가지 조언: working-holiday/22advisetoworholer.md
      - 워홀을 마치며:  working-holiday/23finishingworkingholiday.md
  - Hobby:
    - Motorcycle: motorcycle/index.md
    - Camping: camping/index.md
    - Nightsky:
      - sky/index.md
  - About: eunchan/index.md
extra:
  #alternate:
  #  - name: English
  #    link: /en/
  #    lang: en
  generator: false
  #social:
  #  - type: "linkedin"
  #    link: "https://linkedin.com/in/eunchankim"
repo_url: https://github.com/eunchan/elijah.kim
repo_name: eunchan/elijah.kim
edit_uri: edit/main/docs/
markdown_extensions:
  - attr_list
  - tables
  - footnotes
validation:
  omitted_files: warn
  absolute_links: relative_to_docs
  unrecognized_links: warn
  anchors: warn
copyright: Copyright &copy; 2013 - 2024 Elijah Kim